### ISSUE TITLE
BetterInvites: cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by Razzaline** [domi-btnr/BetterDiscordStuff#32]
### Describe the bug

BetterInvites isn't showing the extended invite information, and outputs an error to console:
```
BetterInvites.plugin.js:173 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prototype')
    at BetterInvites.patchInvite (BetterInvites.plugin.js:173:52)
    at BetterInvites.onStart (BetterInvites.plugin.js:164:22)
    at BetterInvites.start (0PluginLibrary.plugin.js:3663:54)
    at D.startPlugin (renderer.js:5:34310)
    at D.startAddon (renderer.js:5:34103)
    at D.loadAddon (renderer.js:5:6716)
    at D.loadAddon (renderer.js:5:31520)
    at D.loadAllAddons (renderer.js:5:8814)
    at D.initialize (renderer.js:5:3194)
    at D.initialize (renderer.js:5:30719)
```

### How can I recreate this bug

1. Enable the plugin
2. Find a valid invite link
3. Shows default Discord invite info

**Comment by domi-btnr** [comment]
I hope that I can have a look in the next few days/weeks
