### ISSUE TITLE
[Bug]: Message Peek w/ APlatformIndicators causes DM list to disappear

### ISSUE THREAD

**Issue by Moj-FPS** [domi-btnr/BetterDiscordStuff#35]
### Plugin

MessagePeek

### Bug Description

Using APlatformIndicators (by Strencher) alongside MessagePeek causes most of the DM list to disappear. 

### Stacktrace

```code
renderer.js:5 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. t=>Object.values(t).some(e) TypeError: Method %TypedArray%.prototype.join called on incompatible receiver [object Object]
    at Object.join (<anonymous>)
    at Object.toString (<anonymous>)
    at renderer.js:5:44835
    at Array.some (<anonymous>)
    at renderer.js:5:47996
    at renderer.js:5:45760
    at l.getModule (renderer.js:5:47059)
    at l.getWithKey (renderer.js:5:47965)
    at getWithKey.next (<anonymous>)
    at MessagePeek.patchDMs (MessagePeek.plugin.js:515:16)
    at MessagePeek.start (MessagePeek.plugin.js:480:14)
    at N.startPlugin (renderer.js:5:30475)
    at N.startAddon (renderer.js:5:30268)
    at N.enableAddon (renderer.js:5:8942)
    at N.toggleAddon (renderer.js:5:9741)
    at N.togglePlugin (renderer.js:5:27556)
    at renderer.js:5:94370
    at renderer.js:5:126839
    at Object.eY (web.e0be055307495f05a833.js:12:1272403)
    at eX (web.e0be055307495f05a833.js:12:1272557)
    at eJ (web.e0be055307495f05a833.js:12:1272614)
    at rb (web.e0be055307495f05a833.js:12:1293695)
    at ry (web.e0be055307495f05a833.js:12:1294111)
    at web.e0be055307495f05a833.js:12:1299014
    at o9 (web.e0be055307495f05a833.js:12:1364414)
    at eF (web.e0be055307495f05a833.js:12:1271541)
    at rO (web.e0be055307495f05a833.js:12:1295402)
    at t0 (web.e0be055307495f05a833.js:12:1279753)
    at tJ (web.e0be055307495f05a833.js:12:1279537)
_log @ renderer.js:5
renderer.js:5 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. t=>Object.values(t).some(e) TypeError: Method %TypedArray%.prototype.join called on incompatible receiver [object Object]
    at Object.join (<anonymous>)
    at Object.toString (<anonymous>)
    at renderer.js:5:44835
    at Array.some (<anonymous>)
    at renderer.js:5:47996
    at renderer.js:5:45760
    at l.getModule (renderer.js:5:47059)
    at l.getWithKey (renderer.js:5:47965)
    at getWithKey.next (<anonymous>)
    at MessagePeek.patchDMs (MessagePeek.plugin.js:516:16)
    at MessagePeek.start (MessagePeek.plugin.js:480:14)
    at N.startPlugin (renderer.js:5:30475)
    at N.startAddon (renderer.js:5:30268)
    at N.enableAddon (renderer.js:5:8942)
    at N.toggleAddon (renderer.js:5:9741)
    at N.togglePlugin (renderer.js:5:27556)
    at renderer.js:5:94370
    at renderer.js:5:126839
    at Object.eY (web.e0be055307495f05a833.js:12:1272403)
    at eX (web.e0be055307495f05a833.js:12:1272557)
    at eJ (web.e0be055307495f05a833.js:12:1272614)
    at rb (web.e0be055307495f05a833.js:12:1293695)
    at ry (web.e0be055307495f05a833.js:12:1294111)
    at web.e0be055307495f05a833.js:12:1299014
    at o9 (web.e0be055307495f05a833.js:12:1364414)
    at eF (web.e0be055307495f05a833.js:12:1271541)
    at rO (web.e0be055307495f05a833.js:12:1295402)
    at t0 (web.e0be055307495f05a833.js:12:1279753)
    at tJ (web.e0be055307495f05a833.js:12:1279537)
_log @ renderer.js:5
renderer.js:5 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. t=>Object.values(t).some(e) TypeError: Cannot read properties of undefined (reading 'toString')
    at eval (MessagePeek.plugin.js:517:67)
    at Array.some (<anonymous>)
    at renderer.js:5:47996
    at renderer.js:5:45760
    at l.getModule (renderer.js:5:46942)
    at l.getWithKey (renderer.js:5:47965)
    at getWithKey.next (<anonymous>)
    at MessagePeek.patchDMs (MessagePeek.plugin.js:517:16)
    at MessagePeek.start (MessagePeek.plugin.js:480:14)
    at N.startPlugin (renderer.js:5:30475)
    at N.startAddon (renderer.js:5:30268)
    at N.enableAddon (renderer.js:5:8942)
    at N.toggleAddon (renderer.js:5:9741)
    at N.togglePlugin (renderer.js:5:27556)
    at renderer.js:5:94370
    at renderer.js:5:126839
    at Object.eY (web.e0be055307495f05a833.js:12:1272403)
    at eX (web.e0be055307495f05a833.js:12:1272557)
    at eJ (web.e0be055307495f05a833.js:12:1272614)
    at rb (web.e0be055307495f05a833.js:12:1293695)
    at ry (web.e0be055307495f05a833.js:12:1294111)
    at web.e0be055307495f05a833.js:12:1299014
    at o9 (web.e0be055307495f05a833.js:12:1364414)
    at eF (web.e0be055307495f05a833.js:12:1271541)
    at rO (web.e0be055307495f05a833.js:12:1295402)
    at t0 (web.e0be055307495f05a833.js:12:1279753)
    at tJ (web.e0be055307495f05a833.js:12:1279537)
_log @ renderer.js:5
renderer.js:5 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. t=>Object.values(t).some(e) TypeError: Method %TypedArray%.prototype.join called on incompatible receiver [object Object]
    at Object.join (<anonymous>)
    at Object.toString (<anonymous>)
    at renderer.js:5:44835
    at Array.some (<anonymous>)
    at renderer.js:5:47996
    at renderer.js:5:45760
    at l.getModule (renderer.js:5:47059)
    at l.getWithKey (renderer.js:5:47965)
    at getWithKey.next (<anonymous>)
    at MessagePeek.patchGuildChannel (MessagePeek.plugin.js:566:16)
    at MessagePeek.start (MessagePeek.plugin.js:481:14)
    at N.startPlugin (renderer.js:5:30475)
    at N.startAddon (renderer.js:5:30268)
    at N.enableAddon (renderer.js:5:8942)
    at N.toggleAddon (renderer.js:5:9741)
    at N.togglePlugin (renderer.js:5:27556)
    at renderer.js:5:94370
    at renderer.js:5:126839
    at Object.eY (web.e0be055307495f05a833.js:12:1272403)
    at eX (web.e0be055307495f05a833.js:12:1272557)
    at eJ (web.e0be055307495f05a833.js:12:1272614)
    at rb (web.e0be055307495f05a833.js:12:1293695)
    at ry (web.e0be055307495f05a833.js:12:1294111)
    at web.e0be055307495f05a833.js:12:1299014
    at o9 (web.e0be055307495f05a833.js:12:1364414)
    at eF (web.e0be055307495f05a833.js:12:1271541)
    at rO (web.e0be055307495f05a833.js:12:1295402)
    at t0 (web.e0be055307495f05a833.js:12:1279753)
    at tJ (web.e0be055307495f05a833.js:12:1279537)
_log @ renderer.js:5
```

### Confirmation

- [X] I am using the latest version of the plugin
- [X] This issue has not already been reported

**Comment by domi-btnr** [comment]
Hello,

Could you try to screen-record or screenshot the issue? It doesn't happen for me on Canary:

https://github.com/user-attachments/assets/0006ddf9-09a7-4d33-905b-c3cc78327b6c

**Comment by Moj-FPS** [comment]
Hmmm. I just did some more testing and it looks like it's actually another plugin that is causing the issue when both APlatformIndicators and MessagePeek are enabled. APlatformIndicators and MessagePeek seem to work fine together when it's just those two plugins installed. I'll do some more testing in a bit here and see If I can figure out which plugin is causing the error.

**Comment by Moj-FPS** [comment]
However, just for reference, here's a screen clip that shows what it looks like in case you have any ideas what could be causing it.:

https://github.com/user-attachments/assets/4a0b5d66-8abe-473e-aa58-18f39c3b5457

As well as a list of the plugins:

[plugin_files.txt](https://github.com/user-attachments/files/18218884/plugin_files.txt)

I'll let you know what I find!

**Comment by Moj-FPS** [comment]
Well that was quick. Looks like it may be VoiceActivity (by Neodymium). Only happens when all 3 plugins are loaded together. Come to think of it, IIRC APlatformIndicators just had an update to fix a similar issue it had when loaded with VoiceActivity.

**Comment by domi-btnr** [comment]
Sorry for the late response. I completely forgot about this.

I created a PR with the Fix to the VoiceActivtity Plugin. If you want to try it out, you can download it here: [VoiceActivity.plugin.js.txt](https://github.com/user-attachments/files/18736633/VoiceActivity.plugin.js.txt)

You need to remove the `.txt` extension for the plugin to work
